author: Hyperwallet Systems Inc
clean: true
author_url: https://www.hyperwallet.com/
github_file_prefix: https://github.com/hyperwallet/hyperwallet-ios-core-sdk-sandbox
github_url: https://github.com/hyperwallet/hyperwallet-ios-core-sdk-sandbox
copyright: Copyright (c) 2018-present, Hyperwallet Systems Inc. All rights reserved.
module: HyperwalletSDK
module_version: 0.0.1
hide_documentation_coverage: true
podspec: HyperwalletSDK.podspec
readme: README.md
skip_undocumented: true
source_directory: Sources
theme: fullwidth
use_safe_filenames: true
output: docs

custom_categories:
  - children:
      - Hyperwallet
    name: Common
  - children:
      - HyperwalletTransferMethod
      - HyperwalletStatusTransition
      - HyperwalletBankCard
      - HyperwalletBankAccount
      - HyperwalletTransferMethodQueryParam
      - HyperwalletQueryParam
      - HyperwalletPageList
      - HyperwalletBankCardQueryParam
      - HyperwalletBankAccountQueryParam
      - HyperwalletTransferMethodConfigurationFieldQuery
      - HyperwalletTransferMethodConfigurationKeysQuery
      - HyperwalletTransferMethodConfigurationResult
      - HyperwalletTransferMethodConfigurationFieldResult
      - HyperwalletTransferMethodConfigurationKeyResult
      - HyperwalletFee
      - HyperwalletField
      - HyperwalletFieldSelectionOption
      - HyperwalletPageLink
      - HyperwalletPageParameter
      - HyperwalletValidationMessage
      - TransferMethodConfiguration
      - TransferMethodConfigurationTransactionResult
      - GraphQlQuery
    name: Models
  - children:
      - AuthenticationErrorType
      - HyperwalletAuthenticationTokenProvider
    name: Authentication Token Provider
  - children:
      - AuthenticationTokenDecoder
      - Configuration
      - HTTPClient
      - HTTPClientProtocol
      - HTTPMethod
      - HTTPTransaction
      - TransactionType
    name: Helper
  - children:
      - ErrorGroup
      - ErrorType
      - HyperwalletError
      - HyperwalletErrors
    name: Errors
