excluded:
  - Carthage
disabled_rules: # rule identifiers to exclude from running
  - type_body_length
  - file_length
type_name:
    max_length: # warning and error
      warning: 60
      error: 100
identifier_name:
    max_length: # warning and error
      warning: 60
      error: 100
opt_in_rules: # some rules are only opt-in
  - first_where
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - array_init
  - attributes
  - fallthrough
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - override_in_extension
  - pattern_matching_keywords
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - unavailable_function
  - untyped_error_in_catch
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
