lane :beta do
  version = updateVersion("beta")
  update("beta", version)
end

lane :release_beta do
  version = updateVersion("beta")
  commit = last_git_commit
  message = commit[:message]
  add_git_tag(tag: "#{version}", message: "#{message}")
  set_github_release(tag_name: "#{version}", description: "#{message}")
  push_to_git_remote
  pod_push(allow_warnings: true, skip_tests: true)
end

lane :unit_tests do
  run_tests(
    project: "HyperwalletSDK.xcodeproj",
    devices: ['iPhone 15 Pro'],
    derived_data_path: './output',
    scheme: "HyperwalletSDK",
    configuration: 'Debug',
    code_coverage: true,
    xcargs: 'ONLY_ACTIVE_ARCH=YES ENABLE_TESTABILITY=YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO'
  )
end

def updateVersion(type)
  version = last_git_tag
  if type == "beta" then
    version_components = version.split("beta")
    last_component = version_components[-1].to_i + 1
    last_component_string = last_component.to_s
    if last_component_string.size == 1 then
      last_component_string = "0" + last_component_string
    end
    version_components[-1] = last_component_string
    build_version = version_components.join("beta")
  end
end

def update(type, version)
  # Update the TAG_VERSION property
  info_plist_path = "Sources/Info.plist"
  set_info_plist_value(path: info_plist_path, key: "TAG_VERSION", value: version)
  podspec_name = "HyperwalletSDK.podspec"
  pod_lib_lint(allow_warnings: true, skip_tests: true)
  version_bump_podspec(version_number: version, path: podspec_name)
  git_add(path: [podspec_name, info_plist_path, "*.md"])
  git_commit(path: [podspec_name, info_plist_path, "*.md"], message: "#{version} release")
  push_to_git_remote
end
